### ISSUE TITLE
ArchiveRepertory in Omeka 2.6

### ISSUE THREAD

**Issue by WenNg** [Daniel-KM/ArchiveRepertory#5]
I've run ArchiveRepertory in Omeka 2.5 with no problem, and it runs fine when I upgrade from 2.5 to 2.6. But when I download a new v2.6 to test UpgradeToOmekaS, it will show me the following message:

> Could not find file javascripts/vendor/tiny_mce/tiny_mce.js!

I located the file from version 2.5 and copy paste it to the right path in 2.6 folder but Omeka still showing same message.

**Comment by Daniel-KM** [comment]
I check the issue: it is not related to this plugin, since it doesn't use it. Which plugins do you use ? 

Note : I just fixed an issue on UpgradeToOmekaS.

**Comment by theecrit** [comment]
@Daniel-KM When you do have a chance to verify that 2.15.2 is compatible with Omeka 2.6, will you be noting that anywhere? Just wondering when I should check back. Thanks!!

**Comment by WenNg** [comment]
These are the plugins that I had on the v2.6; it's lesser compared to the other version of Omeka classic I had. 
ArchiveRepertory | 2.15.2
CollectionTree | 2.1
CsvImport | 2.0.4
CsvImportPlus | 2.3.3
DublinCoreExtended | 2.2
SimplePages | 3.1
UniversalViewer | 2.4.6
UpgradeToOmekaS | 2.1

**Comment by kokomokoso** [comment]
Omeka 2.6 has a new tinymce version. I change this code: 
/views/admin/plugins/archive-repertory-config-form.php
#309: <?php echo js_tag('vendor/tinymce/tinymce.min'); ?>
and then run ArchiveRepertory.
Sorry for my bad english

**Comment by Daniel-KM** [comment]
The plugin is fixed for Omeka 2.6 in the new release 2.15.3.

**Comment by theecrit** [comment]
Thank you, all!

**Comment by zerocrates** [comment]
The zipped release currently uploaded as 2.15.3 is actually the Omeka S module version of this plugin

**Comment by Daniel-KM** [comment]
Thanks, this is fixed.
